# Change this to change what browser books are opened in on run by default.
default_browser = "xdg-open"

# The least-recently-opened cached book will be purged when at least one of
#   these limits is reached. (If a single book is larger than the max bytes, it
#   will purge all prior books on opening, and will be purged as soon as any
#   other book is open.) Either of these maximums will be ignored if set to 0.
max_cache_books = 50
max_cache_bytes = 1_000_000_000 # 1 GB

# Change this to change which of the stylesheets defined below is used by
#   default.
default_stylesheet = "null"

[stylesheets]
    # Each stylesheet has a variety of potential keys. If a key is undefined
    #   in a given stylesheet, no CSS related to that key will be injected.
    #
    # Each key comes with two sub-keys, 'value' and 'override_book'.
    # 'value' is the key's value. Type varies by key.
    # 'override_book' determines whether the key's associated style
    #   should override, or be overridden by, styles set by the book itself.
    #   It's a bool.
    #
    # List of supported keys:
    # font: string, CSS font-family to use.
    # font_size: int, font size in px.
    # text_color: string, CSS color name or code to use for ordinary text.
    # link_color: string, CSS color name or code to use for hyperlink text.
    # background_color: string, CSS color name or code to use for page
    #   background color.
    # line_spacing: float, CSS line-height value. (1.0 means ~traditional
    #   single-spacing, 2.0 means ~traditional double-spacing, et cetera.)
    # indentation: int, start-of-paragraph indentation in px. (CSS text-indent.)
    # margin_size: int, page left and right margin size in px.
    # max_width: int, maximum reading-column width in px.
    # limit_image_size_to_viewport_size: bool, set CSS image max-width and
    #   max-height to 100% if true.
    #
    # Each stylesheet also supports keys freeform_css_no_override and
    #   freeform_css_override. These are strings of arbitrary CSS, respectively
    #   to be injected without and with override_book_stylesheets behavior
    [stylesheets.null]
        # This space intentionally left blank.
    [stylesheets.basalt]
        [stylesheets.basalt.font_size]
            value = 16
            override_book = false
        [stylesheets.basalt.text_color]
            value = "gold" # #FFD700
            override_book = false
        [stylesheets.basalt.link_color]
            value = "orangered" # #FF4500
            override_book = false
        [stylesheets.basalt.background_color]
            value = "darkslateblue" # #483D8B
            override_book = false
        [stylesheets.basalt.margin_size]
            value = 8
            override_book = false
        [stylesheets.basalt.limit_image_size_to_viewport_size]
            value = true
            override_book = true
